(lang dune 3.21)

(name custom_target)

(generate_opam_files false)

(source
 (github username/reponame))

(authors "Author Name <author@example.com>")

(maintainers "Maintainer Name <maintainer@example.com>")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name custom_target)
 (description "Testing broken package with working dependencies")
 (depends (ocaml (>= 5.6.0)) base64))
