(lang dune 3.21)

(name foo)

(generate_opam_files false)

(source
 (github username/reponame))

(authors "Author Name <author@example.com>")

(maintainers "Maintainer Name <maintainer@example.com>")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name foo)
 (depends ocaml bar))

(pin
 (url ../bar)
 (package (name bar)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
