(lang dune 3.24)

(name non_portable_ocaml)

(generate_opam_files false)

(source
 (github username/reponame))

(authors "Author Name <author@example.com>")

(maintainers "Maintainer Name <maintainer@example.com>")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name non_portable_ocaml)
 (synopsis "A short synopsis")
 (description "A longer description")
 ;; Pin to the last non-portable version (pre-5.5.0)
 (depends (ocaml (= 5.4.0)))
 (tags
  ("add topics" "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
