name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  nocommit:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - uses: nobssoftware/nocommit@5c3cf9519fe40b80b0954d254085b67b532a5dc3

  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15
      - uses: cachix/cachix-action@3ba601ff5bbb07c7220846facfa2cd81eeee15a1
        if: github.repository_owner == 'anteriorcore'
        with:
          name: anterior-private
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix flake check -L

  nix-flake-show:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - uses: nixbuild/nix-quick-install-action@c57091870f58910a7aef53a0b0a99f6ba568aa6f
      - run: nix flake show
